"""model created

Revision ID: 58fbd131b0eb
Revises: 8749e4332a9d
Create Date: 2024-02-01 14:00:59.406831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58fbd131b0eb'
down_revision: Union[str, None] = '8749e4332a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('name', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('movie', sa.Column('seen', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('posted_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('movie', sa.Column('like', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('movie', 'Seen')
    op.drop_column('movie', 'Price')
    op.drop_column('movie', 'Like')
    op.drop_column('movie', 'Posted_at')
    op.drop_column('movie', 'Description')
    op.drop_column('movie', 'Name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('Posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('Like', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('Price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('Seen', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'price')
    op.drop_column('movie', 'like')
    op.drop_column('movie', 'posted_at')
    op.drop_column('movie', 'seen')
    op.drop_column('movie', 'description')
    op.drop_column('movie', 'name')
    # ### end Alembic commands ###
