"""model created

Revision ID: 6b85ecf1aaee
Revises: edab8f8b4d5d
Create Date: 2024-02-01 16:29:40.245511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b85ecf1aaee'
down_revision: Union[str, None] = 'edab8f8b4d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_video', sa.Column('hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'movie_video', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_video', type_='unique')
    op.drop_column('movie_video', 'hash')
    # ### end Alembic commands ###
