"""model created

Revision ID: d11e4ee4adda
Revises: 6b85ecf1aaee
Create Date: 2024-02-01 16:43:02.398812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11e4ee4adda'
down_revision: Union[str, None] = '6b85ecf1aaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_video')
    op.add_column('movie', sa.Column('video', sa.String(), nullable=True))
    op.add_column('movie', sa.Column('hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'movie', ['hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='unique')
    op.drop_column('movie', 'hash')
    op.drop_column('movie', 'video')
    op.create_table('movie_video',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='movie_video_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='movie_video_pkey'),
    sa.UniqueConstraint('hash', name='movie_video_hash_key')
    )
    # ### end Alembic commands ###
